### ISSUE TITLE
Mixing function and getter with self store reference broke intelisence

### ISSUE THREAD

**Issue by jonlepage** [RisingStack/react-easy-state#177]
**React Easy State version:** 	"@risingstack/react-easy-state": "^6.2.0",
**Platform:** nwjs, nodejs

**Describe the bug**
Mix `Function` + `Getters` in Objet littéral seem broken intelligences if we add store references inside methods !
The store alway show `Any`
Any way to fix this ?
![image](https://user-images.githubusercontent.com/24865815/80271170-b3013b80-868b-11ea-8987-d2c509f38bbf.png)

After deep investigations, it seem only append if we mix getter,function, and both have store reference
![agt34gtab](https://user-images.githubusercontent.com/24865815/80271501-ac27f800-868e-11ea-9ba7-826ec50b489b.gif)
Plz play with this code in vscode, to see the strange biavior
```js

export const _store = store({
	/** comments or replace `return _store` will unbreak intelisence ref  */
	get getter1() { return _store },
	get getter2() { return _store },
    /** comments or replace `return _store` will unbreak intelisence ref  */
	getChildrensFrom1(param) { return _store },
	getChildrensFrom2(param) { return _store },
});
```
**Edit:** just for comfirm it come from `React-Easy-State`, i try simple obj litteral out the store, and it work fine.
![image](https://user-images.githubusercontent.com/24865815/80271741-438e4a80-8691-11ea-9ffa-4b841dab3114.png)

------------

here the log of vscode debbuger
But it maybe not related , but i share juste in case it can help !
Maybe something bad in your `type.d.ts`
```json
 ERR Unexpected token, expected ";" (2:24)
  1 | /* @babel/template */;
> 2 | 	getChildrensFrom(node) {
    | 	                      ^
  3 | 		node.map((key) => Store_DataBaseStorage.data[key]);
  4 | 	},: SyntaxError: Unexpected token, expected ";" (2:24)
  1 | /* @babel/template */;
> 2 | 	getChildrensFrom(node) {
    | 	                      ^
  3 | 		node.map((key) => Store_DataBaseStorage.data[key]);
  4 | 	},
	at _class.raise (c:\Users\InformatiqueLepage\.vscode\extensions\wix.glean-4.21.1\node_modules\@babel\parser\lib\index.js:3939:15)
	at _class.unexpected (c:\Users\InformatiqueLepage\.vscode\extensions\wix.glean-4.21.1\node_modules\@babel\parser\lib\index.js:5248:16)
	at _class.semicolon (c:\Users\InformatiqueLepage\.vscode\extensions\wix.glean-4.21.1\node_modules\@babel\parser\lib\index.js:5232:40)
	at _class.parseExpressionStatement (c:\Users\InformatiqueLepage\.vscode\extensions\wix.glean-4.21.1\node_modules\@babel\parser\lib\index.js:7665:10)
	at _class.parseExpressionStatement (c:\Users\InformatiqueLepage\.vscode\extensions\wix.glean-4.21.1\node_modules\@babel\parser\lib\index.js:9980:69)
	at _class.parseStatementContent (c:\Users\InformatiqueLepage\.vscode\extensions\wix.glean-4.21.1\node_modules\@babel\parser\lib\index.js:7264:19)
	at _class.parseStatementContent (c:\Users\InformatiqueLepage\.vscode\extensions\wix.glean-4.21.1\node_modules\@babel\parser\lib\index.js:9916:58)
	at _class.parseStatement (c:\Users\InformatiqueLepage\.vscode\extensions\wix.glean-4.21.1\node_modules\@babel\parser\lib\index.js:7145:17)
	at _class.parseBlockOrModuleBlockBody (c:\Users\InformatiqueLepage\.vscode\extensions\wix.glean-4.21.1\node_modules\@babel\parser\lib\index.js:7696:23)
	at _class.parseBlockBody (c:\Users\InformatiqueLepage\.vscode\extensions\wix.glean-4.21.1\node_modules\@babel\parser\lib\index.js:7683:10)
	at _class.parseTopLevel (c:\Users\InformatiqueLepage\.vscode\extensions\wix.glean-4.21.1\node_modules\@babel\parser\lib\index.js:7110:10)
	at _class.parse (c:\Users\InformatiqueLepage\.vscode\extensions\wix.glean-4.21.1\node_modules\@babel\parser\lib\index.js:8510:17)
	at parse (c:\Users\InformatiqueLepage\.vscode\extensions\wix.glean-4.21.1\node_modules\@babel\parser\lib\index.js:10465:38)
	at parseWithCodeFrame (c:\Users\InformatiqueLepage\.vscode\extensions\wix.glean-4.21.1\node_modules\@babel\template\lib\parse.js:145:32)
	at parseAndBuildMetadata (c:\Users\InformatiqueLepage\.vscode\extensions\wix.glean-4.21.1\node_modules\@babel\template\lib\parse.js:43:15)
	at c:\Users\InformatiqueLepage\.vscode\extensions\wix.glean-4.21.1\node_modules\@babel\template\lib\string.js:21:50
	at Function.ast (c:\Users\InformatiqueLepage\.vscode\extensions\wix.glean-4.21.1\node_modules\@babel\template\lib\builder.js:47:155)
	at Object.exports.templateToAst (c:\Users\InformatiqueLepage\.vscode\extensions\wix.glean-4.21.1\out\parsing.js:22:52)
	at Object.isStatelessComp (c:\Users\InformatiqueLepage\.vscode\extensions\wix.glean-4.21.1\out\modules\statless-to-stateful.js:20:27)
	at CompleteActionProvider.provideCodeActions (c:\Users\InformatiqueLepage\.vscode\extensions\wix.glean-4.21.1\out\extension.js:30:36)
	at c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:631:432
	at c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:54:761
	at new Promise (<anonymous>)
	at Object.t.asPromise (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:54:733)
	at e.provideCodeActions (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:631:403)
	at c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:654:385
	at e._withAdapter (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:649:159)
	at e.$provideCodeActions (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:654:363)
	at e._doInvokeHandler (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:752:683)
	at e._invokeHandler (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:752:375)
	at e._receiveRequest (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:750:953)
	at e._receiveOneMessage (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:749:832)
	at c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:748:34
	at e.fire (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:497)
	at v.fire (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:206:615)
	at c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:919:744
	at e.fire (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:497)
	at v.fire (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:206:615)
	at t.PersistentProtocol._receiveMessage (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:211:17)
	at c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:208:155
	at e.fire (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:497)
	at p.acceptChunk (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:204:129)
	at c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:203:483
	at Socket.t (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:212:565)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by solkimicreb** [comment]
I will look into it. Which version of easy state are you using?

**Comment by solkimicreb** [comment]
Could you try it with v6.3.0 (latest)?

**Comment by jonlepage** [comment]
i just made the update.
uncomfortably same behavior for the `6.3.0` .
![image](https://user-images.githubusercontent.com/24865815/80277601-1c01a700-86be-11ea-9223-1c8c4d7fd084.png)

**Comment by jonlepage** [comment]
For the moment I avoid mixing the 2, but it could become annoying if the need arises.
It really not urgent and low priority, just if you have the time or find the problem by black magic, it will be great. :)

Thank you for your excellent libraries, it's really great, I can't stand Redux and its logic !

**Comment by solkimicreb** [comment]
I am still trying to understand what's happening but it seems like to be a TypeScript limitation about circularity.

Try to use `this` instead of direct references (`_store`) inside getters and setters (keep using `_store` inside normal methods though). That should fix it without any behavior change.

I will let you know once I figure out what exactly is happening.
