### ISSUE TITLE
expo+react-native+jest: unit testing is failing "ReferenceError: You are trying to `import` a file after the Jest environment has been torn down."

### ISSUE THREAD

**Issue by seyaobey** [RisingStack/react-easy-state#219]
**React Easy State version:** ^6.3.0
**Platform:** react-native (expo)

**Describe the bug**
I'm trying to run a simple test against a component which consumes a local store:
`test.tsx`
```
test('my test', () => {
   const local = store({
     values: { username: 'foo' }
  }); 

  const { getByText } = render(
     <Form store={store}>
        <TextInput name='username' />
     </Form>);

  expect(getByText("foo")).toBe(true);
})
```

I'm unable to run unit tests: it fails with errors inside the `react-easy-state` code:

```
 RUNS  src/components/form/form.test.tsx

node_modules/@risingstack/react-easy-state/dist/cjs.es6.js:243 <--
    return reactPlatform_cjs.unstable_batchedUpdates(() => fn.apply(ctx, args));

ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.
      at Object.get unstable_batchedUpdates [as unstable_batchedUpdates] (node_modules/react-native/index.js:312:12)
      at Object.unstable_batchedUpdates (node_modules/@risingstack/react-easy-state/dist/react-platform.cjs.native.js:13:22) <--
      at batch (node_modules/@risingstack/react-easy-state/src/batch.js:21:12)
      at Object.apply (node_modules/@risingstack/react-easy-state/src/batch.js:40:16)

TypeError: reactPlatform_cjs.unstable_batchedUpdates is not a function
    at batch (node_modules/@risingstack/react-easy-state/src/batch.js:21:12) <--
    at Object.apply (node_modules/@risingstack/react-easy-state/src/batch.js:40:16)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:494:7)
```

Here is my unit test setup:

`package.json`

```
...
"expo": "~38.0.8",
"react": "~16.11.0",
"react-dom": "~16.11.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",
"@testing-library/jest-native": "^3.4.3",
"@testing-library/react-native": "^7.0.2",
"jest-expo": "^39.0.0",
"react-test-renderer": "^16.13.1",
"typescript": "~3.9.5",
```

`jest.config.js`

```
module.exports = {
  preset: 'jest-expo',
  transformIgnorePatterns: [
    "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base)"
  ]
};
```

**Expected behavior**
Unit tests should run with crashing

**Comment by seyaobey** [comment]
I solved the issue by addind

`jest.useFakeTimers();`
see https://stackoverflow.com/questions/50793885/referenceerror-you-are-trying-to-import-a-file-after-the-jest-environment-has

Not sure if this is due to an error in my setting or is this something to keep in mind when unit testing with jest + react-easy-state
